### ISSUE TITLE
Close resolved RT bugs

### ISSUE THREAD

**Issue by mcmillhj** [Perl-Toolchain-Gang/Parse-CPAN-Meta#10]
There are several bugs listed on RT that have already been resolved:

[rt77447](https://rt.cpan.org/Public/Bug/Display.html?id=77447) was fixed in v1.4414
[rt67324](https://rt.cpan.org/Public/Bug/Display.html?id=67324) appears to have been fixed in v1.38
[rt94900](https://rt.cpan.org/Public/Bug/Display.html?id=94900) was fixed in v1.4411

**Comment by dagolden** [comment]
All marked closed.  Thanks for doing the research.
