### ISSUE TITLE
bizarre dependency upgrade issue with portable windows perls

### ISSUE THREAD

**Issue by wchristian** [Perl-Toolchain-Gang/Parse-CPAN-Meta#11]
Short version: Upgrading dep CPAN::Meta::YAML from 0.08 to 0.14, with PCM 1.4404 installed breaks installation of cpan modules.

Reproduction steps:

1. download http://strawberryperl.com/download/5.16.3.1/strawberry-perl-5.16.3.1-32bit-portable.zip
2. unpack it to d:\strawberry-perl-5.16.3.1-32bit-portable
2.a) it comes with CPAN::Meta::YAML 0.08 and PCM 1.4404
3. start cpan
4. look CPAN::Meta
5. verify that the newest CPAN::Meta requires an upgrade of PCM
6. look PCM
7. verify that the newest PCM requires an upgrade of CMY
8. cpan Test::More
9. cpan Devel::StackTrace # ony to verify that Test::More
10. verify that cpan only wrote to d:\strawberry-perl-5.16.3.1-32bit-portable\cpan\* and not to c:\strawberry
11. cpan CPAN::Meta::YAML
12. cpan Devel::StackTrace
13. observe that cpan wrote to c:\strawberry
14. rm d:\strawberry-perl-5.16.3.1-32bit-portable\perl\site\lib\CPAN\Meta\YAML.pm
15. cpan Devel::StackTrace
16. observe that cpan is back to writing to d:\strawberry-perl-5.16.3.1-32bit-portable\cpan\*

**Comment by wchristian** [comment]
As per request:

(@xdg) Mithaldu, after step 11, if you "look Devel::StackTrace" and run "perl Makefile.PL" can you post the output and the resulting Makefile?

https://gist.github.com/wchristian/e285ef40a76e4563a157

**Comment by haarg** [comment]
Strawberry has a YAML config file which is used to set up its portable config.  It has a duplicate key: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/master/share/portable/portable.perl.32#L29-30

The portable config is loaded and used from within Config.pm.  Older versions of strawberry use CPAN::Meta::YAML via Parse::CPAN::Meta to load the config file.  Newer versions of CPAN::Meta::YAML throw errors on duplicate keys.  This was added in CPAN::Meta::YAML 0.013, generated from YAML::Tiny 1.65.  Newer versions of strawberry have their own inlined YAML parser, so they aren't affected by changes to CPAN::Meta::YAML.

**Comment by dagolden** [comment]
Awesome diagnosis!  I'm not sure what to do about it, other than have YAML::Tiny stop following that aspect of the YAML spec, but I'm not sure that's a great idea.

**Comment by dolmen** [comment]
@haarg ++

**Comment by ribasushi** [comment]
@haarg++ indeed.

> other than have YAML::Tiny stop following that aspect of the YAML spec 

How... did we get "from here to there"? The problematic module in question is `CPAN::Meta::YAML`, the entire purpose of which is to... parse CPAN META. The fact that it is a doppelgänger of `YAML::Tiny` is an implementation detail and should in no way affect the practical utility of C::M::Y.

As far as the question of relaxing the check within C::M::Y itself, it is a no-brainer to me: what good is standardizing toolchain on something which fails on contact with some aspects of the outside world?

I feel like I am missing something substantial here...

**Comment by wchristian** [comment]
@haarg: Wow, thanks for figuring that out. I'll try and patch that here
this afternoon and report back.

**Comment by haarg** [comment]
@ribasushi: Keep in mind that in this case, CPAN::Meta::YAML is being used as a generic YAML parser, not to load a META file.

**Comment by ribasushi** [comment]
> ... is being used as a generic YAML parser, not to load a META file ...

@haarg Ah! That's indeed what I've missed. The rest of my comment stands though - turning C::M::Y into a "lax parser" (still a good idea imo) has no bearing on YAML::Tiny.

**Comment by wchristian** [comment]
I retract my former post. In light of CMY just being some kind of clone of YAML::Tiny cobbled together at release time, i have no idea how to patch this, aside from patching Y::T with an option to handle dups differently, updating CMY, then patching PCM to send that option and dep on the newest.

Maybe?

I'll leave doing that to people who know what they're doing.

**Comment by xdg** [comment]
I'm not opposed to YAML::Tiny gaining a lax option, and having PCM flip it
on, but does Strawberry use PCM or CMY?

**Comment by rjbs** [comment]
> As far as the question of relaxing the check within C::M::Y itself, it is a no-brainer to me: what good is standardizing toolchain on something which fails on contact with some aspects of the outside world?

"Lax in what you accept" is good, but I'm reticent to see a change to what is accepted just for one file.  Is this a generic problem?  It looks like a human error when someone edited a datafile by hand.  Where would we draw the line between "you really mangled the input" and "you mangled it but we'll cope" when it comes to this stuff?  I'm not sure, but my instinct is to be slow to introduce new laxness.

**Comment by xdg** [comment]
We were lax before and then YT got strict.  That's not quite the same.

I'm mixed still.

**Comment by ribasushi** [comment]
> I'm reticent to see a change to what is accepted just for one file.

When put this way it indeed sounds like shitty engineering. Or you can put it in the actual context of:

> I'm reticent to see a change to what is accepted just for one file... which happens to be shipped with an untold number of strawberry-perl-5.16.3.1-portable installations

In which case the question becomes "who is this tooling for in the first place?".

@rjbs There is no line to be drawn, the PTG serves at the pleasure of the end user.

**Comment by xdg** [comment]
Strawberry could also ship a fix, though.

**Comment by ribasushi** [comment]
> Strawberry could also ship a fix, though.

Of course they could, and they in essence did: 
> ... Newer versions of strawberry have their own inlined YAML parser...

Except (sorry for repointing the obvious) this in no way helps existing users (which is also users of images with this perl baked in), who happen to touch CPAN.

**Comment by wchristian** [comment]
Yeah, fixing strawberry would be possible, but it would need to be applied to a big number of installers/archives, since versions before 16.3 are also afflicted. Further, there is no way to simply go "upgrade this perl installation to the next point upgrade", which means current users are at risk of having their installation blown up on a tiny upgrade forced via dep chain, with the only recourse to somehow figure out they need to manually adapt that one file, or blow everything away and reinstall everything on a higher perl.

**Comment by rjbs** [comment]
So, sincere question: Strawberry Perl does not have a mechanism to self-update itself in ways other than "I want to upgrade perl"?  I don't know how the Perl-Dist-Strawberry dist is used.  This is not something that could, itself, be upgraded in place?

Is the Config that's loading the yaml-ish file Perl's own Config.pm, patched to do so?  (I had also wondered whether that could be taught to account for this specific error.)

My point is not that nothing should be lax, but that the effect on the toolchain should be proportionate.  Every time we add a general laxity to account for some specific problem, we're also hiding other problems that we didn't know about.  Years later, we find that we have a large amount of complexity in place to handle bad data that would not have continued to exist had they been flagged to begin with.

So:  can we deal with this problem without adding a universally present laxity?  This is my question.

**Comment by dagolden** [comment]
Now that I'm back on a physical keyboard, here are my expanded thoughts.

* The idea of YAML::Tiny was to implement a *subset* of YAML -- i.e. avoid things that were complex and largely unnecessary (e.g. references); the goal was *not* to implement it poorly or incorrectly or laxly.
* The PCM/CMY wrapping/rebadging of YAML::Tiny exist for mostly two reasons: (a) because Ingy didn't want a not-quite-YAML blessed by core; (b) CMY has the *option* to actually fork should that become necessary.  It was not *intended* as a fork and I wouldn't want it to go that way.
* Catching previously uncaught YAML errors is not a backwards-incompatible change in the same way that prohibiting previously legal YAML or removing a supported feature would be.
* That said, duplicate keys are not so much a technical error (causing an improper parse) as a semantic ambiguity that JSON allows (as does Perl for hashes) and that YAML forbids.  So laxity in duplicate keys actually improves the equivalence to JSON, which could have useful interoperability benefits.
* The point of ::Tiny is to minimize knobs/options/variations.  Adding an option to allow duplicate keys is un-tiny bloat, even if useful.
* Allowing duplicate keys in META and other CMY-targeted YAML means that producers can be lazy and keep using illegal YAML. That makes it harder to use faster and more-correct (libyaml) implementations to parse them.
* Allowing duplicate keys makes it easier to correctly clean up such errors: read lax, write strict.

I lean towards adding a duplicate-allowed option to YAML::Tiny, but I'm not sold on it being turned on by default in CMY or PCM.

But if added, then I suspect it might be a trivial one-liner to sanitize the bad YAML file in Strawberry, which gives people a way to unwedge themselves.

And, possibly, possibly, the CMY installer could detect a portable strawberry and fix it on install.  That might be too crazy, but I lean towards that over allowing universal laxity.

**Comment by wchristian** [comment]
Some partial thoughts:

@rjbs: There is no way to upgrade affected installations, short of automatically patching the file "portable.perl" at runtime. There simply isn't.

@xdg: A more concrete bug here is: The failure to parse that file is somehow silenced. I am not clear at which point the silencing happens, but maybe it is a bug in whatever used cmy?

**Comment by dagolden** [comment]
@wchristian: by 'upgrade' I thought @rjbs meant upgrade in the way Windows apps upgrade, eg with a new MSI that can fix the installed file without blowing away sitelib or whatever.

Without downloading an affected Strawberry, I can't dig into the silencing or decide what a quick patch might look like, and I'm too short of tuits this month to do that.

**Comment by wchristian** [comment]
I know what kind of patching he meant. Not possible, and even if it were you'd need to find a way to communicate that at runtime to the user, which equates to fixing the silencing.

**Comment by ribasushi** [comment]
> ...
> ... I'm not sold on it being turned on by default in CMY or PCM.

Given the expanded 7-bullet list, I am completely baffled how the above is still a question. At this point I don't think there is much else to add from my side.

**Comment by wchristian** [comment]
@ribasushi Tbh, your post is fairly ambiguous. I have no idea what you are advocating and ask you to please put it on less prosaic terms.

**Comment by ribasushi** [comment]
> @ribasushi Tbh, your post is fairly ambiguous. I have no idea what you are advocating and ask you to please put it on less prosaic terms.

`CPAN::Meta::YAML` must revert to allowing duplicate keys by default. Anything else is a non-option.

**Comment by karenetheridge** [comment]
> CPAN::Meta::YAML must revert to allowing duplicate keys by default. Anything else is a non-option.

Leaving aside what the "correct" option is -- *are* there any other options that are actually technically possible? I can't think of any, if it's not possible to patch that problematic data file in a way that doesn't require manual intervention.

**Comment by dagolden** [comment]
Putting on my albatross, I think the argument is "this specific problem is just one example of how stricter parsing for no great reason can break something".

Can someone please verify whether the affected Strawberry is using Parse::CPAN::Meta or CPAN::Meta::YAML?

**Comment by haarg** [comment]
@wchristian: The failure is silenced because Portable is loaded in an eval.  Look in `strawberry-perl-5.16.3.1-32bit-portable\perl\lib\Config.pm`.

@dagolden: It uses Parse::CPAN::Meta.  Config.pm calls `Portable->import`.  https://metacpan.org/source/KMX/Portable-1.18/lib/Portable.pm

**Comment by ingydotnet** [comment]
If it's of any help, I disagree with the spec re duplicate keys. The spec should effectively say that YAML's data model does not support duplicate keys, but that it is not mandatory to forbid them. I went into more detail on my thought process in irc.

I personally would not detect duplicate keys. Currently only YAML::Tiny does this. The other implementations do differ in which value they load, but I think that's fine. Use dups at your own peril.

I will be actively pushing for new rules in the spec on this. For now, if removing that patch fixes things, do it now! (Please)

**Comment by wchristian** [comment]
A note from IRC: It might be valuable to downgrade the die on dup to a warn on dup.

**Comment by ingydotnet** [comment]
Actually I think it is OK to warn, die or do nothing. I don't think the dieing was the bad thing here. The masking of it in an eval was. However it might be best to have all the Big 4 YAMLs doing the same thing.

**Comment by dagolden** [comment]
OK.  For now, I propose s/die/warn/ in YAML::Tiny.  Then later, the various YAML implementations can harmonize.

Could someone with tuits please make it so?

**Comment by ingydotnet** [comment]
Sounds good. I have the tuits but I don't know how to get the thing all the way upstream. I skipped my salmon classes in skool.

**Comment by karenetheridge** [comment]
*puts on fishie hat*

- someone submits a PR; gets @ingydotnet and kibbitzers to approve it
- @karenetheridge (or someone else with comaint, if they want) ships YAML-Tiny
- @dagolden or other comaintainer ships CPAN-Meta-YAML
- profit?

**Comment by dagolden** [comment]
s/die/warn/ is a one line change.  Fixing the test is the more complicated bit or I'd have done it by now but I don't have the tuits to dig into it.

**Comment by karenetheridge** [comment]
I've made the change in the `topic/warn_hash_dup` branch, including what I *think* should be all the necessary test changes, but this doesn't currently work yet -- I can't get the new t/tml-local/load-warning/document.tml test to run.  I'll need another set of eyes on this to spot the error, and then I can pretty it up for merging.

https://github.com/Perl-Toolchain-Gang/YAML-Tiny/tree/topic/warn_hash_dup

**Comment by karenetheridge** [comment]
Fixed in https://github.com/Perl-Toolchain-Gang/YAML-Tiny/tree/topic/warn_hash_dup -- @ingy, @dagolden please review.

I wonder if YAML::Tiny should use its own warnings category, so callers can easily silence these warnings if desired.

**Comment by dagolden** [comment]
I don't think we should add a warnings category (expected to be rare and not ::Tiny).

I've reviewed @karenetheridge's patch and LTGM.  I think it can ship and then I'll update CMY.

**Comment by karenetheridge** [comment]
ok, I'll start up the release engines!

**Comment by karenetheridge** [comment]
uploaded at 19:06 PDT:  http://metacpan.org/release/DAGOLDEN/CPAN-Meta-YAML-0.015-TRIAL

**Comment by wchristian** [comment]
Just retested it with that version and strawberry behaves now.

**Comment by dagolden** [comment]
I'll ship stable next week when I can watch for any problems.

**Comment by haarg** [comment]
I've filed https://rt.cpan.org/Ticket/Display.html?id=104467 regarding the duplicate entries in the portable.perl file.

**Comment by haarg** [comment]
CPAN-Meta-YAML 0.16 stable shipped on May 19, which resolved this issue.
