### ISSUE TITLE
Plan for merging Parse-CPAN-Meta into CPAN-Meta

### ISSUE THREAD

**Issue by xdg** [Perl-Toolchain-Gang/Parse-CPAN-Meta#13]
We currently have a devrel smoking (1.4420).  Assuming it goes well, I'd like to do one final, stable release of Parse-CPAN-META as a standalone unit.

In the meantime, I'll start up a branch in CPAN-Meta that brings in the PCM code and tests and does any harmonization necessary.  After the stable PCM release, I'd like to release a devrel of CPAN-Meta with PCM included.

If that goes well, we can ship a stable CPAN-Meta, and put an EOL notice on this repo.

Any thoughts?  Speak now/soon or hold your peace.

**Comment by Leont** [comment]
I think the only feature of this split was that PCM once worked on 5.6 while CPAN::Meta never did, however we lost that two years ago and no one notices, so I guess that's a moot point.

**Comment by xdg** [comment]
Yes, and since the split, toolchain agreed on 5.8.1 as the target.  At this point, managing them separately is more trouble than help, particularly given the coupling between JSON/YAML backend environment variables.

For anyone just joining this issue, this was also covered on the CPAN-Meta side as Perl-Toolchain-Gang/CPAN-Meta#58

**Comment by kentfredric** [comment]
I think I may have noticed at some point, but the standard "if I care enough to make this happen, I have to submit the patch" applies there.

**Comment by Leont** [comment]
Supporting Parse::CPAN::Meta without supporting CPAN::Meta is just not terribly useful unless there were parts of the toolchain that used PCM instead of CM for exactly this reason.

**Comment by xdg** [comment]
Done!
