### ISSUE TITLE
failure to parse numeric 0 in values

### ISSUE THREAD

**Issue by karenetheridge** [Perl-Toolchain-Gang/Parse-CPAN-Meta#7]
I got this failure report:

http://www.cpantesters.org/cpan/report/535f86e4-4b51-11e4-bcbe-97ef48525b5c

```
, or } expected while parsing object/hash, at character offset 163 (before ""generated_by" : "Di...") at /home/njh/perl5/perlbrew/perls/perl-5.8.1/lib/site_perl/5.8.1/Parse/CPAN/Meta.pm line 52.
 at /home/njh/perl5/perlbrew/perls/perl-5.8.1/lib/site_perl/5.8.1/CPAN/Meta.pm line 300.
```

The relevant bit of YAML-Tiny-1.63/META.json is:

```
   "dynamic_config" : 0,
   "generated_by" : "Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520",
```

Can Parse::CPAN::Meta not always handle numeric (as opposed to stringified) has values?

I see a few issues in the code:
- the json backend in use is not being included in the error message
- only JSON::PP and JSON.pm are being used; we should at least support JSON::XS and Cpanel::JSON::XS as well, as JSON.pm is less encouraged now in favour of the XS backends that have more current bug fixes
- JSON::PP is being used *first*, when it should be used only as a last resort

**Comment by xdg** [comment]
Should be fixed with the prereq bump in master
